// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckOvertrading() {
  return window['go']['main']['App']['CheckOvertrading']();
}

export function CloseTrade(arg1, arg2, arg3) {
  return window['go']['main']['App']['CloseTrade'](arg1, arg2, arg3);
}

export function ContributeToGoal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ContributeToGoal'](arg1, arg2, arg3);
}

export function CreateGoal(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateGoal'](arg1, arg2, arg3);
}

export function CreateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4);
}

export function CreateTrade(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['CreateTrade'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetGoals() {
  return window['go']['main']['App']['GetGoals']();
}

export function GetIndianMarketNews() {
  return window['go']['main']['App']['GetIndianMarketNews']();
}

export function GetMonthlyStats() {
  return window['go']['main']['App']['GetMonthlyStats']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetThisWeekChecklist() {
  return window['go']['main']['App']['GetThisWeekChecklist']();
}

export function GetTodayChecklist() {
  return window['go']['main']['App']['GetTodayChecklist']();
}

export function GetTodayTrades() {
  return window['go']['main']['App']['GetTodayTrades']();
}

export function GetTrades(arg1) {
  return window['go']['main']['App']['GetTrades'](arg1);
}

export function GetTradingSettings() {
  return window['go']['main']['App']['GetTradingSettings']();
}

export function GetTradingStats(arg1, arg2) {
  return window['go']['main']['App']['GetTradingStats'](arg1, arg2);
}

export function UpdateDailyChecklist(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateDailyChecklist'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateTaskStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskStatus'](arg1, arg2);
}

export function UpdateTradingSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTradingSettings'](arg1, arg2, arg3);
}

export function UpdateWeeklyChecklist(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateWeeklyChecklist'](arg1, arg2, arg3, arg4, arg5);
}
