// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {main} from '../models';
import {broker} from '../models';

export function AuthorizeUpstox(arg1:number,arg2:string):Promise<void>;

export function CheckAnalyticsTokenStatus():Promise<Record<string, any>>;

export function CheckOvertrading():Promise<Record<string, any>>;

export function CloseTrade(arg1:number,arg2:number,arg3:string):Promise<void>;

export function ContributeToGoal(arg1:number,arg2:number,arg3:number):Promise<void>;

export function CreateGoal(arg1:string,arg2:number,arg3:any):Promise<void>;

export function CreateTask(arg1:string,arg2:string,arg3:string,arg4:any):Promise<void>;

export function CreateTrade(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number,arg7:string,arg8:string,arg9:string,arg10:string,arg11:number,arg12:string):Promise<number>;

export function DeleteBrokerConfig(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetAllBrokerConfigs():Promise<Array<database.BrokerConfig>>;

export function GetBrokerConfig(arg1:string):Promise<database.BrokerConfig>;

export function GetGoals():Promise<Array<database.Goal>>;

export function GetIndianMarketNews():Promise<Array<main.NewsArticle>>;

export function GetMarketQuoteWithAnalyticsToken(arg1:string,arg2:string):Promise<broker.MarketQuote>;

export function GetMonthlyStats():Promise<Record<string, any>>;

export function GetPortfolioWithAnalyticsToken():Promise<Array<broker.Position>>;

export function GetRecentLogs(arg1:number):Promise<Array<Record<string, any>>>;

export function GetSyncedTrades(arg1:number,arg2:number):Promise<Array<database.SyncedTrade>>;

export function GetTasks():Promise<Array<database.Task>>;

export function GetThisWeekChecklist():Promise<database.WeeklyChecklist>;

export function GetTodayChecklist():Promise<database.DailyChecklist>;

export function GetTodayTrades():Promise<Array<database.Trade>>;

export function GetTrades(arg1:number):Promise<Array<database.Trade>>;

export function GetTradesWithAnalyticsToken():Promise<Array<broker.Trade>>;

export function GetTradingSettings():Promise<database.TradingSettings>;

export function GetTradingStats(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetUpstoxAuthURL(arg1:string,arg2:string):Promise<string>;

export function GetUpstoxMarketQuote(arg1:string,arg2:string):Promise<broker.MarketQuote>;

export function GetUpstoxPositions(arg1:number):Promise<Array<broker.Position>>;

export function GetUserProfileWithAnalyticsToken():Promise<broker.UserProfile>;

export function SaveBrokerConfig(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean,arg6:number):Promise<void>;

export function SyncUpstoxTrades(arg1:number):Promise<Record<string, any>>;

export function UpdateBrokerConfig(arg1:number,arg2:string,arg3:string,arg4:boolean,arg5:boolean,arg6:number):Promise<void>;

export function UpdateDailyChecklist(arg1:number,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean,arg6:boolean,arg7:boolean):Promise<void>;

export function UpdateTaskStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateTradingSettings(arg1:number,arg2:number,arg3:number):Promise<void>;

export function UpdateWeeklyChecklist(arg1:number,arg2:boolean,arg3:boolean,arg4:boolean,arg5:string):Promise<void>;
