// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDeposit(arg1, arg2) {
  return window['go']['main']['App']['AddDeposit'](arg1, arg2);
}

export function AddTaskLog(arg1, arg2) {
  return window['go']['main']['App']['AddTaskLog'](arg1, arg2);
}

export function AddWithdrawal(arg1, arg2) {
  return window['go']['main']['App']['AddWithdrawal'](arg1, arg2);
}

export function AuthorizeUpstox(arg1, arg2) {
  return window['go']['main']['App']['AuthorizeUpstox'](arg1, arg2);
}

export function CheckAnalyticsTokenStatus() {
  return window['go']['main']['App']['CheckAnalyticsTokenStatus']();
}

export function CheckOvertrading() {
  return window['go']['main']['App']['CheckOvertrading']();
}

export function CloseTrade(arg1, arg2, arg3) {
  return window['go']['main']['App']['CloseTrade'](arg1, arg2, arg3);
}

export function ContributeToGoal(arg1, arg2) {
  return window['go']['main']['App']['ContributeToGoal'](arg1, arg2);
}

export function CreateChecklistItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateChecklistItem'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateGoal(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateGoal'](arg1, arg2, arg3);
}

export function CreateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4);
}

export function CreateTrade(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['CreateTrade'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function DeleteBrokerConfig(arg1) {
  return window['go']['main']['App']['DeleteBrokerConfig'](arg1);
}

export function DeleteChecklistItem(arg1) {
  return window['go']['main']['App']['DeleteChecklistItem'](arg1);
}

export function DeleteGoal(arg1) {
  return window['go']['main']['App']['DeleteGoal'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DeleteTrade(arg1) {
  return window['go']['main']['App']['DeleteTrade'](arg1);
}

export function GetAllBrokerConfigs() {
  return window['go']['main']['App']['GetAllBrokerConfigs']();
}

export function GetBrokerConfig(arg1) {
  return window['go']['main']['App']['GetBrokerConfig'](arg1);
}

export function GetCapitalTransactions(arg1) {
  return window['go']['main']['App']['GetCapitalTransactions'](arg1);
}

export function GetChecklistItems(arg1) {
  return window['go']['main']['App']['GetChecklistItems'](arg1);
}

export function GetCurrentCapitalBalance() {
  return window['go']['main']['App']['GetCurrentCapitalBalance']();
}

export function GetDailyPLData(arg1) {
  return window['go']['main']['App']['GetDailyPLData'](arg1);
}

export function GetGoals() {
  return window['go']['main']['App']['GetGoals']();
}

export function GetIndianMarketNews() {
  return window['go']['main']['App']['GetIndianMarketNews']();
}

export function GetMarketQuoteWithAnalyticsToken(arg1, arg2) {
  return window['go']['main']['App']['GetMarketQuoteWithAnalyticsToken'](arg1, arg2);
}

export function GetMonthlyStats() {
  return window['go']['main']['App']['GetMonthlyStats']();
}

export function GetOAuthCode() {
  return window['go']['main']['App']['GetOAuthCode']();
}

export function GetPaperTradingMode() {
  return window['go']['main']['App']['GetPaperTradingMode']();
}

export function GetPortfolioWithAnalyticsToken() {
  return window['go']['main']['App']['GetPortfolioWithAnalyticsToken']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetSyncedTrades(arg1, arg2) {
  return window['go']['main']['App']['GetSyncedTrades'](arg1, arg2);
}

export function GetTaskLogs(arg1) {
  return window['go']['main']['App']['GetTaskLogs'](arg1);
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetThisWeekChecklist() {
  return window['go']['main']['App']['GetThisWeekChecklist']();
}

export function GetTodayChecklist() {
  return window['go']['main']['App']['GetTodayChecklist']();
}

export function GetTodayTrades() {
  return window['go']['main']['App']['GetTodayTrades']();
}

export function GetTrades(arg1) {
  return window['go']['main']['App']['GetTrades'](arg1);
}

export function GetTradesWithAnalyticsToken() {
  return window['go']['main']['App']['GetTradesWithAnalyticsToken']();
}

export function GetTradingSettings() {
  return window['go']['main']['App']['GetTradingSettings']();
}

export function GetTradingStats(arg1, arg2) {
  return window['go']['main']['App']['GetTradingStats'](arg1, arg2);
}

export function GetUpstoxAuthURL(arg1, arg2) {
  return window['go']['main']['App']['GetUpstoxAuthURL'](arg1, arg2);
}

export function GetUpstoxMarketNews() {
  return window['go']['main']['App']['GetUpstoxMarketNews']();
}

export function GetUpstoxMarketQuote(arg1, arg2) {
  return window['go']['main']['App']['GetUpstoxMarketQuote'](arg1, arg2);
}

export function GetUpstoxPositions(arg1) {
  return window['go']['main']['App']['GetUpstoxPositions'](arg1);
}

export function GetUserProfileWithAnalyticsToken() {
  return window['go']['main']['App']['GetUserProfileWithAnalyticsToken']();
}

export function SaveBrokerConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveBrokerConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetPaperTradingMode(arg1) {
  return window['go']['main']['App']['SetPaperTradingMode'](arg1);
}

export function SyncUpstoxTrades(arg1) {
  return window['go']['main']['App']['SyncUpstoxTrades'](arg1);
}

export function UpdateBrokerConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateBrokerConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateChecklistItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateChecklistItem'](arg1, arg2, arg3, arg4);
}

export function UpdateDailyChecklist(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateDailyChecklist'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateGoal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateGoal'](arg1, arg2, arg3, arg4);
}

export function UpdateTaskProgress(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskProgress'](arg1, arg2);
}

export function UpdateTaskStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskStatus'](arg1, arg2);
}

export function UpdateTrade(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) {
  return window['go']['main']['App']['UpdateTrade'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
}

export function UpdateTradingSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTradingSettings'](arg1, arg2, arg3);
}

export function UpdateTradingSettingsWithProtection(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateTradingSettingsWithProtection'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateWeeklyChecklist(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateWeeklyChecklist'](arg1, arg2, arg3, arg4, arg5);
}

export function WaitForOAuthCode(arg1) {
  return window['go']['main']['App']['WaitForOAuthCode'](arg1);
}
